version: 2
updates:
  # Configuration template for any angular examples
  - package-ecosystem: "npm"
    directory: "/angular/*" # Pattern matching for directory names
    schedule:
      interval: "daily"
  # Configuration template for any react examples
  - package-ecosystem: "npm"
    directory: "/react/*" # Pattern matching for directory names
    schedule:
      interval: "daily"