version: 2
updates:
  # Configuration template for any angular examples
  - package-ecosystem: "npm"
    directory: "/angular/alpha-angular"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/angular/alpha-handle-events"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/angular/basic"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/angular/showcase"
    schedule:
      interval: "weekly"
  # Configuration template for any react examples
  - package-ecosystem: "npm"
    directory: "/react/alpha-react"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/react/alpha-handle-events"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/react/basic"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/react/showcase"
    schedule:
      interval: "weekly"