import reactifyWc from 'reactify-wc';
import style from './FormsPage.module.css';
import {
  JSON_SCHEMA,
  JSON_SCHEMA_ARRAY,
  JSON_SCHEMA_ARRAY_TRADE,
  JSON_SCHEMA_CATEGORIZATION,
  JSON_SCHEMA_CONNECTED_NUMBER,
  JSON_SCHEMA_CONNECTED_SELECT,
  JSON_SCHEMA_GROUP,
  JSON_SCHEMA_STEPPER,
  uiSchema,
  uiSchemaArray,
  uiSchemaArrayTrade,
  uiSchemaCategorization,
  uiSchemaConnectedNumber,
  uiSchemaConnectedSelect,
  uiSchemaConnectedSelectAsync,
  uiSchemaGroup,
  uiSchemaStepper,
  uiSchemaStepperHorizontal,
} from './schemas';

const FoundationForm: any = reactifyWc('foundation-form');

const FormsPage = () => {
  const formWithDSPrefixData = {
    ISSUER_NAME: 'Some Issuer',
    INVIS: 'Invisible value!',
    USER: 'JohnDoe',
    DATE: 1690848000000,
  };

  return (
    <zero-tabs class={style['forms-page']}>
      <span slot="start">Foundation Forms</span>
      <zero-tab>Primitive Renderers</zero-tab>
      <zero-tab>Connected Renderers</zero-tab>
      <zero-tab>Array Renderer</zero-tab>
      <zero-tab>Group Renderer</zero-tab>
      <zero-tab>Categorization Renderer</zero-tab>
      <zero-tab>Stepper Renderer</zero-tab>
      <zero-tab>Autogenerated UI Schema clipboard</zero-tab>
      <zero-tab>Foundation Forms with DS prefix</zero-tab>

      <zero-tab-panel>
        <div className={style['form-container']}>
          <h2>Primitive Renderers</h2>
          <div style={{ display: 'flex', flexDirection: 'row' }}>
            <FoundationForm
              uischema={uiSchema}
              jsonSchema={JSON_SCHEMA}
            ></FoundationForm>
          </div>
        </div>
      </zero-tab-panel>
      <zero-tab-panel>
        <div className={style['form-container']}>
          <h2>Examples</h2>
          <h3>1. Connected Combobox/Multiselect</h3>
          <FoundationForm
            uischema={uiSchemaConnectedSelect}
            jsonSchema={JSON_SCHEMA_CONNECTED_SELECT}
          ></FoundationForm>
          <h3>2. Connected Combobox/Multiselect with async mode</h3>
          <FoundationForm
            jsonSchema={JSON_SCHEMA_CONNECTED_SELECT}
            uischema={uiSchemaConnectedSelectAsync}
          ></FoundationForm>
          <h3>3. Connected Combobox with local data</h3>
          <FoundationForm
            jsonSchema={JSON_SCHEMA_CONNECTED_NUMBER}
            uischema={uiSchemaConnectedNumber}
            data={{
              NUMBER_RATE: 0,
            }}
          ></FoundationForm>
        </div>
      </zero-tab-panel>
      <zero-tab-panel>
        <div className={style['form-container']}>
          <h2>Examples</h2>
          <h3>1. User Array Form</h3>
          <FoundationForm
            data={{
              users: [
                {
                  firstname: 'John',
                  lastname: 'Doe',
                  email: 'john@doe.com',
                  rights: 'ADMIN',
                },
              ],
            }}
            uischema={uiSchemaArray}
            jsonSchema={JSON_SCHEMA_ARRAY}
          ></FoundationForm>
          <h3>1. Trade Array Form</h3>
          <FoundationForm
            data={{
              users: [
                {
                  instrumentId: 'VOD',
                  quantity: '500',
                  side: 'BUY',
                },
              ],
            }}
            uischema={uiSchemaArrayTrade}
            jsonSchema={JSON_SCHEMA_ARRAY_TRADE}
          ></FoundationForm>
        </div>
      </zero-tab-panel>
      <zero-tab-panel>
        <div className={style['form-container']}>
          <h2>Example</h2>
          <FoundationForm
            uischema={uiSchemaGroup}
            jsonSchema={JSON_SCHEMA_GROUP}
            data={{
              person: { firstName: 'John' },
              address: { city: 'London' },
            }}
            design-system-prefix="fast"
          ></FoundationForm>
        </div>
      </zero-tab-panel>
      <zero-tab-panel>
        <div className={style['form-container']}>
          <h2>Example</h2>
          <zero-card style={{ width: '50%', padding: '0 15px' }}>
            <FoundationForm
              uischema={uiSchemaCategorization}
              jsonSchema={JSON_SCHEMA_CATEGORIZATION}
            ></FoundationForm>
          </zero-card>
        </div>
      </zero-tab-panel>
      <zero-tab-panel>
        <div className={style['form-container']}>
          <h2>Examples</h2>
          <h3>1. Vertical Stepper Form</h3>
          <FoundationForm
            uischema={uiSchemaStepper}
            jsonSchema={JSON_SCHEMA_STEPPER}
            style={{ height: '400px' }}
            hide-submit-button
          ></FoundationForm>
          <h3>2. Horizontal Stepper Form</h3>
          <FoundationForm
            uischema={uiSchemaStepperHorizontal}
            jsonSchema={JSON_SCHEMA_STEPPER}
            style={{ height: '500px' }}
            hide-submit-button
          ></FoundationForm>
        </div>
      </zero-tab-panel>
      <zero-tab-panel>
        <div className={style['form-container']}>
          <h2>Autogenerated UI Schema clipboard on DEV mode</h2>
          <div style={{ display: 'flex', flexDirection: 'row' }}>
            <foundation-form resourceName="EVENT_INSTRUMENT_INSERT"></foundation-form>
          </div>
        </div>
      </zero-tab-panel>
      <zero-tab-panel>
        <div className={style['form-container']}>
          <h2>Foundation Forms with DS prefix</h2>
          <div style={{ display: 'flex', flexDirection: 'row' }}>
            <FoundationForm
              jsonSchema={JSON_SCHEMA}
              uischema={uiSchema}
              data={formWithDSPrefixData}
              design-system-prefix="fast"
            ></FoundationForm>
          </div>
        </div>
      </zero-tab-panel>
    </zero-tabs>
  );
};

export default FormsPage;
